.
.TH "GNOME\-CATGEN" "" "June 2014" "" "gnome\-catgen"
A Gnome 3\.12 Folder Category Configuration Tool
.
.SH "Configuration"
.
.SS "Interactive Category Selection"
While configuration is primarily done by hand, running \fBgnome\-catgen \-c\fR or \fBgnome\-catgen \-\-choose\-remaining\fR will begin iterating through the list of applications that aren\'t currently in a folder and let you choose where you would like them to go\.
.
.P
In this mode you can do the following:
.
.IP "\(bu" 4
Enter the name of a folder category to add the current application\.
.
.IP "\(bu" 4
Enter a blank line to skip the current application\.
.
.IP "\(bu" 4
Press ctrl\-c to quit at any time\.
.
.IP "" 0
.
.P
Once all the applications without a folder have been cycled through, \fBgnome\-catgen\fR will offer the option of applying the changes you just made to your config\. If you choose not to apply the changes at this point, you can do so later by running: \fBgnome\-catgen \-s\fR\.
.
.SS "Configure Category Files"
To configure the folder category for each application, (if necessary) create and browse to: \fB~/\.local/share/applications\-categories\fR
.
.IP "1." 4
In here, create files with the \fB\.category\fR extension and the name of the category they will represent\.
.
.IP "2." 4
Inside \fB\.category\fR files, one application\'s \.desktop filename can be added to each line, to add the application to that folder category\.
.
.IP "3." 4
Once everything is configured how you\'d like it, run: \fBgnome\-catgen set\fR to apply your configuration\.
.
.IP "" 0
.
.SS "Editing Category Files"
.
.IP "\(bu" 4
Blank lines are ignored\.
.
.IP "\(bu" 4
Lines where the first non\-whitespace character is a # considered commented and are ignored\.
.
.IP "" 0
.
.SH "Commands"
.
.SS "Read"
.
\fBgnome\-catgen \-f\fR | \fB\-\-get\-folders\fR
.RS 4
List current folders
.RE
.PP

\fBgnome\-catgen \-a\fR | \fB\-\-get\-apps\fR
.RS 4
List current apps in each folder
.RE
.PP

\fBgnome\-catgen \-r\fR | \fB\-\-get\-remaining\fR
.RS 4
List apps without a folder
.RE
.PP

\fBgnome\-catgen \-g\fR | \fB\-\-get\fR
.RS 4
List all of the above
.RE
.PP
.
.IP "" 0
.
.SS "Write"
.
\fBgnome\-catgen \-s\fR | \fB\-\-set\fR
.RS 4
Apply current folder configuration
.RE
.PP

\fBgnome\-catgen \-x\fR | \fB\-\-clear\fR
.RS 4
Remove applied folder configuration
.RE
.PP

\fBgnome\-catgen \-c\fR | \fB\-\-choose\-remaining\fR
.RS 4
Interactively assign folders to apps without
.RE
.PP
.
.IP "" 0
.
.SS "Info"
.
\fBgnome\-catgen \-h\fR | \fB\-\-help\fR
.RS 4
Display the list of commands.
.RE
.PP
.
.IP "" 0
.
.SH "CREDITS"
Written by Kevin MacMartin:
.
.IP "\(bu" 4
GitHub Projects \fIhttps://github\.com/prurigro\fR
.
.IP "\(bu" 4
Arch Linux AUR Packages \fIhttps://aur\.archlinux\.org/packages/?SeB=m&K=prurigro\fR
.
.IP "" 0
.
.SH "LICENSE"
Licensed under the MIT license \fIhttp://opensource\.org/licenses/MIT\fR\.
