.if !\n(.g \{\
.	if !\w|\*(lq| \{\
.		ds lq ``
.		if \w'\(lq' .ds lq "\(lq
.	\}
.	if !\w|\*(rq| \{\
.		ds rq ''
.		if \w'\(rq' .ds rq "\(rq
.	\}
.\}
.ie t .ds Tx \s-1T\v'.4n'\h'-.1667'E\v'-.4n'\h'-.125'X\s0
. el  .ds Tx TeX
.de Id
. ds Yr \\$4
. substring Yr 0 3
. ds Mn \\$4
. substring Mn 5 6
. ds Dy \\$4
. substring Dy 8 9
. \" ISO 8601 date, complete format, extended representation
. ds Dt \\*(Yr-\\*(Mn-\\*(Dy
..
.TH GNOME\-CATGEN 1 \*(Dt "gnome-catgen (git)" "User Commands"
.hy 0
.
.SH "NAME"
.B gnome\-catgen
\- a gnome 3\.12 and 3\.14 folder category configuration tool
.
.SH "SYNOPSIS"
.
.B gnome\-catgen
.RI [COMMAND]
.
.P
.B gnome\-catgen
.RI [COMMAND]
.RB {CAT}
.
.SH "CONFIGURATION"
.
.SS "Interactive Category Selection"
While configuration is done primarily by hand, it\'s possible to iterate through the list of applications that aren\'t already in a folder category and select a category for each by running: \fB\'gnome\-catgen \-c\'\fR
.P
In this mode you can do the following:
.
.IP "\(bu" 2
Enter the name of a folder category to add the current application\.
.
.IP "\(bu" 2
Enter a blank line to skip the current application\.
.
.IP "\(bu" 2
Press ctrl\-c to quit at any time\.
.
.P
Once all the applications without a folder have been cycled through, \fBgnome\-catgen\fR will offer to apply the updated configuration\. Choosing not to apply the changes at this time will simply exit the program, and the changes can then be applied later by running: \fBgnome\-catgen \-s\fR\.
.
.SS "Configure Category Files"
You can manually configure a given folder category by running: gnome-catgen \-e "Category Name"
.P
This will create (if it doesn't already exist) and open (with the editor set by \fB$EDITOR\fR\, or \fBvi\fR if nothing is set) the \fB\'\.category\'\fR file in \fB\'~/\.local/share/applications\-categories\'\fR for the provided category name. In this file, you can now add one application\'s \fB\'\.desktop\'\fR filename per line\. After all the desired applications have been added, you can then run: \fBgnome\-catgen \-s\fR to apply your configuration\.
.
.SS "Notes on Category Files"
.
.IP "\(bu" 2
Blank lines are ignored\.
.
.IP "\(bu" 2
Lines where the first non\-whitespace character is a # considered commented and are ignored\.
.
.SH "COMMANDS"
.
.SS "Read"
.TP
.BR \-f ", " \-\^\-get\-folders
List current folders
.TP
.TP
.BR \-a ", " \-\^\-get\-apps
List current apps in each folder
.TP
.TP
.BR \-r ", " \-\^\-get\-remaining
List apps without a folder
.TP
.TP
.BR \-g ", " \-\^\- get
List all of the above
.SS "Edit"
.TP
.BR \-c ", " \-\^\-choose\-remaining
Interactively assign folders to apps without
.TP
.TP
.BR \-e " {CAT}, " \-\^\-edit\-category " {CAT}"
edit the .category file of the folder category for {CAT}.
.SS "Write"
.TP
.BR \-s ", " \-\^\-set
Apply current folder configuration
.TP
.TP
.BR \-x ", " \-\^\-clear
Remove applied folder configuration
.SS "Information"
.TP
.BR \-h ", " \-\^\-help
Display the list of commands.
.
.SH "GENERAL NOTES"
.TP
.IP "\(bu" 2
If there are still uncategorized apps and gnome-catgen -c doesn't list them, there may be something unexpected in ~/.local/share/applications-categories, and an easy fix is to delete/backup and start again.
.
.IP "\(bu" 2
It may be necessary to delete/backup ~/.local/share/applications-categories when upgrading from Gnome 3.12 to 3.14 for reasons related to the note above.
.
.SH "CREDITS"
Written by Kevin MacMartin:
.
.IP "\(bu" 2
GitHub Projects \fIhttps://github\.com/prurigro\fR
.
.IP "\(bu" 2
Arch Linux AUR Packages \fIhttps://aur\.archlinux\.org/packages/?SeB=m&K=prurigro\fR
.
.SS "CONTRIBUTORS"
.
Florian Rommel (utivis)
.P
Martin Lukeš (meridius)
.
.SH "LICENSE"
Released under the MIT license \fIhttp://opensource\.org/licenses/MIT\fR\.
